version: '3'
services:
  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - 8080:80
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on: 
      - phpfpm
  phpfpm:
    build: ./phpfpm
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    volumes:
      - ./app:/var/www/html
    depends_on: 
      - db
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8888:80
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    depends_on:
      - db
networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24